// <auto-generated />
using System;
using Jellyfin.Plugin.SegmentRecognition.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Jellyfin.Plugin.SegmentRecognition.Data.Migrations
{
    [DbContext(typeof(SegmentDbContext))]
    partial class SegmentDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.4");

            modelBuilder.Entity("Jellyfin.Plugin.SegmentRecognition.Data.Entities.AnalysisStatus", b =>
                {
                    b.Property<Guid>("ItemId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AnalyzedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasResults")
                        .HasColumnType("INTEGER");

                    b.HasKey("ItemId", "ProviderName");

                    b.HasIndex("ItemId");

                    b.ToTable("AnalysisStatuses");
                });

            modelBuilder.Entity("Jellyfin.Plugin.SegmentRecognition.Data.Entities.BlackFrameResult", b =>
                {
                    b.Property<Guid>("ItemId")
                        .HasColumnType("TEXT");

                    b.Property<long>("TimestampTicks")
                        .HasColumnType("INTEGER");

                    b.Property<double>("BlackPercentage")
                        .HasColumnType("REAL");

                    b.Property<string>("ConfigHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("ItemId", "TimestampTicks");

                    b.HasIndex("ItemId");

                    b.ToTable("BlackFrameResults");
                });

            modelBuilder.Entity("Jellyfin.Plugin.SegmentRecognition.Data.Entities.ChapterAnalysisResult", b =>
                {
                    b.Property<Guid>("ItemId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SegmentType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MatchedChapterName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConfigHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("EndTicks")
                        .HasColumnType("INTEGER");

                    b.Property<long>("StartTicks")
                        .HasColumnType("INTEGER");

                    b.HasKey("ItemId", "SegmentType", "MatchedChapterName");

                    b.HasIndex("ItemId");

                    b.ToTable("ChapterAnalysisResults");
                });

            modelBuilder.Entity("Jellyfin.Plugin.SegmentRecognition.Data.Entities.ChromaprintResult", b =>
                {
                    b.Property<Guid>("ItemId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Region")
                        .HasColumnType("TEXT");

                    b.Property<int>("AnalysisDurationSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConfigHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("FingerprintData")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("TEXT");

                    b.HasKey("ItemId", "Region");

                    b.HasIndex("SeasonId");

                    b.ToTable("ChromaprintResults");
                });

            modelBuilder.Entity("Jellyfin.Plugin.SegmentRecognition.Data.Entities.CropDetectResult", b =>
                {
                    b.Property<Guid>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CropHeight")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CropWidth")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CropX")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CropY")
                        .HasColumnType("INTEGER");

                    b.HasKey("ItemId");

                    b.ToTable("CropDetectResults");
                });
#pragma warning restore 612, 618
        }
    }
}
