name: 'Build Plugin'

on:
  push:
    branches: [ "master", "analyzers" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Embed version info
      run: echo "${{ github.sha }}" > Jellyfin.Plugin.SegmentRecognition/Configuration/version.txt

    - name: Build
      run: dotnet build --no-restore

    - name: Upload artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: intro-skipper-${{ github.sha }}.dll
        path: Jellyfin.Plugin.SegmentRecognition/bin/Debug/net6.0/Jellyfin.Plugin.SegmentRecognition.dll
        if-no-files-found: error
