# Allows for the definition of PR and Issue /commands
name: 'Slash Command Dispatcher'

permissions: {}

on:
  issue_comment:
    types:
      - created

jobs:
  command-dispatch:
    uses: jellyfin/jellyfin-meta-plugins/.github/workflows/command-dispatch.yaml@master
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
