name: 'Sync labels'

permissions:
  issues: write

on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  sync-labels:
    uses: jellyfin/jellyfin-meta-plugins/.github/workflows/sync-labels.yaml@master
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
